#!/bin/bash

# TelePilot Installation - Ready to Execute
echo "🚀 TelePilot Installation Steps"
echo "================================"

echo "📋 STEP 1: Git Commit & Push"
echo "Run these commands in your terminal:"
echo ""
echo "# Add updated package.json"
echo "git add package.json"
echo ""
echo "# Commit changes"  
echo 'git commit -m "🚀 Add TelePilot community node for crypto signal monitoring"'
echo ""
echo "# Push to remote"
echo "git push origin main"
echo ""

echo "📋 STEP 2: Environment Variable in Render"
echo "1. Go to https://dashboard.render.com"
echo "2. Find your iqv2-n8n-bot service"
echo "3. Click on service"
echo "4. Go to 'Environment' tab"
echo "5. Add Environment Variable:"
echo "   Name: N8N_COMMUNITY_PACKAGES"
echo "   Value: [\"@telepilotco/n8n-nodes-telepilot\"]"
echo "6. Click 'Save Changes'"
echo ""

echo "📋 STEP 3: Wait for Deployment"
echo "- Render will auto-deploy (5-10 minutes)"
echo "- Watch for 'Build successful' in logs"
echo ""

echo "📋 STEP 4: Verify Installation"
echo "1. Go to https://iqv2.onrender.com"
echo "2. Login: iqv2admin / Iqv2N8N!2024Secure"
echo "3. Settings → Community Nodes"
echo "4. Should show: @telepilotco/n8n-nodes-telepilot (INSTALLED)"
echo "5. New Workflow → Add Node → Search 'teleport'"
echo "6. Should show: TelePilot Trigger, TelePilot Action"
echo ""

echo "✅ SUCCESS INDICATORS:"
echo "- Package.json includes: @telepilotco/n8n-nodes-telepilot"
echo "- Render deployment successful"
echo "- n8n Community Nodes shows installed"
echo "- TelePilot nodes available in Add Node dialog"
echo ""

echo "🔄 ALTERNATIVE: If TelePilot still doesn't work"
echo "Use Telegram Bot API instead:"
echo "1. @BotFather → /newbot"
echo "2. Add bot to @shervin_trading, @uniopn"
echo "3. Use native Telegram Trigger in n8n"
echo ""

echo "Press Enter when you've completed STEP 1 (git push)"
echo "Press Enter again when you've completed STEP 2 (environment variable)"
echo "Press Enter when deployment is complete"