services:
  - type: web
    name: iqv2-n8n-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "10000"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        fromService:
          type: secret
          name: n8n-basic-auth-user
          property: value
      - key: N8N_BASIC_AUTH_PASSWORD
        fromService:
          type: secret
          name: n8n-basic-auth-password
          property: value
      - key: N8N_ENCRYPTION_KEY
        fromService:
          type: secret
          name: n8n-encryption-key
          property: value

databases:
  - name: n8n-db
    databaseName: n8n
    user: n8n